# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: MVC

on:
  push:
    branches:
      - mvc
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release ./Contact/Contact.MVC

      - name: dotnet publish
        run: dotnet publish -c Release -o /home/runner/.dotnet/myapp/Contact.MVC
        working-directory: ./Contact/Contact.MVC

      - name: List contents of /home/runner/.dotnet/myapp directory
        run: ls -al /home/runner/.dotnet/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: /home/runner/.dotnet/myapp/Contact.MVC

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'test-contact-api'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_0E2D795E69774BBCB7C3CBF9B038BC18 }}
          package: /home/runner/work/contact/contact
